
INSERT INTO T_Comments_Closure(ancestor, descendant, depth) VALUES (1, 1, 0);
INSERT INTO T_Comments_Closure(ancestor, descendant, depth) VALUES (1, 2, 1);
INSERT INTO T_Comments_Closure(ancestor, descendant, depth) VALUES (1, 3, 2);
INSERT INTO T_Comments_Closure(ancestor, descendant, depth) VALUES (1, 4, 1);
INSERT INTO T_Comments_Closure(ancestor, descendant, depth) VALUES (1, 5, 2);
INSERT INTO T_Comments_Closure(ancestor, descendant, depth) VALUES (1, 6, 2);
INSERT INTO T_Comments_Closure(ancestor, descendant, depth) VALUES (1, 7, 3);
INSERT INTO T_Comments_Closure(ancestor, descendant, depth) VALUES (2, 2, 0);
INSERT INTO T_Comments_Closure(ancestor, descendant, depth) VALUES (2, 3, 1);
INSERT INTO T_Comments_Closure(ancestor, descendant, depth) VALUES (3, 3, 0);
INSERT INTO T_Comments_Closure(ancestor, descendant, depth) VALUES (4, 4, 0);
INSERT INTO T_Comments_Closure(ancestor, descendant, depth) VALUES (4, 5, 1);
INSERT INTO T_Comments_Closure(ancestor, descendant, depth) VALUES (4, 6, 1);
INSERT INTO T_Comments_Closure(ancestor, descendant, depth) VALUES (4, 7, 2);
INSERT INTO T_Comments_Closure(ancestor, descendant, depth) VALUES (5, 5, 0);
INSERT INTO T_Comments_Closure(ancestor, descendant, depth) VALUES (6, 6, 0);
INSERT INTO T_Comments_Closure(ancestor, descendant, depth) VALUES (6, 7, 1);
INSERT INTO T_Comments_Closure(ancestor, descendant, depth) VALUES (7, 7, 0);
