

-- Pluggable_Authentication_Modules.html

CREATE TABLE dbo.T_PEM
(
	 PEM bigint NOT NULL
	,CONSTRAINT PK_T_PEM PRIMARY KEY(PEM)
);

GO

CREATE TABLE dbo.T_User
(
	 USR_PEM_UID bigint NOT NULL CONSTRAINT FK_T_User_T_PEM FOREIGN KEY(USR_PEM_UID) REFERENCES dbo.T_PEM(PEM) ON DELETE CASCADE 
	,CONSTRAINT PK_T_User PRIMARY KEY(USR_PEM_UID) 
);

GO 
